server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: seguridad-service
          uri: lb://seguridad-service
          predicates:
            - Path=/auth/**

        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
          filters:
            - AuthenticationFilter            

        - id: carro-service
          uri: lb://carro-service
          predicates:
            - Path=/carro/**
          filters:
            - AuthenticationFilter
           
        - id: moto-service
          uri: lb://moto-service
          predicates:
            - Path=/moto/**
          filters:
            - AuthenticationFilter

        - id: bicicleta-service
          uri: lb://bicicleta-service
          predicates:
            - Path=/bicicleta/**
          filters:
            - AuthenticationFilter